// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: accountextensions.go

package types

import (
	"bytes"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *AccountCreateExtensions) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *AccountCreateExtensions) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ `)
	if j.NullExt != nil {
		if true {
			buf.WriteString(`"null_ext":`)

			{

				err = j.NullExt.MarshalJSONBuf(buf)
				if err != nil {
					return err
				}

			}
			buf.WriteByte(',')
		}
	}
	if j.OwnerSpecialAuthority != nil {
		if true {
			buf.WriteString(`"owner_special_authority":`)

			{

				obj, err = j.OwnerSpecialAuthority.MarshalJSON()
				if err != nil {
					return err
				}
				buf.Write(obj)

			}
			buf.WriteByte(',')
		}
	}
	if j.ActiveSpecialAuthority != nil {
		if true {
			buf.WriteString(`"active_special_authority":`)

			{

				obj, err = j.ActiveSpecialAuthority.MarshalJSON()
				if err != nil {
					return err
				}
				buf.Write(obj)

			}
			buf.WriteByte(',')
		}
	}
	if j.BuybackOptions != nil {
		if true {
			buf.WriteString(`"buyback_options":`)

			{

				err = j.BuybackOptions.MarshalJSONBuf(buf)
				if err != nil {
					return err
				}

			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtAccountCreateExtensionsbase = iota
	ffjtAccountCreateExtensionsnosuchkey

	ffjtAccountCreateExtensionsNullExt

	ffjtAccountCreateExtensionsOwnerSpecialAuthority

	ffjtAccountCreateExtensionsActiveSpecialAuthority

	ffjtAccountCreateExtensionsBuybackOptions
)

var ffjKeyAccountCreateExtensionsNullExt = []byte("null_ext")

var ffjKeyAccountCreateExtensionsOwnerSpecialAuthority = []byte("owner_special_authority")

var ffjKeyAccountCreateExtensionsActiveSpecialAuthority = []byte("active_special_authority")

var ffjKeyAccountCreateExtensionsBuybackOptions = []byte("buyback_options")

// UnmarshalJSON umarshall json - template of ffjson
func (j *AccountCreateExtensions) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *AccountCreateExtensions) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtAccountCreateExtensionsbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit