// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: block.go

package types

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *Block) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *Block) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"witness":`)

	{

		obj, err = j.Witness.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"transaction_merkle_root":`)

	{

		obj, err = j.TransactionMerkleRoot.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"witness_signature":`)

	{

		obj, err = j.WitnessSignature.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"previous":`)

	{

		obj, err = j.Previous.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"block_id":`)

	{

		obj, err = j.BlockID.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"timestamp":`)

	{

		obj, err = j.TimeStamp.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.SigningKey != nil {
		if true {
			buf.WriteString(`"signing_key":`)

			{

				obj, err = j.SigningKey.MarshalJSON()
				if err != nil {
					return err
				}
				buf.Write(obj)

			}
			buf.WriteByte(',')
		}
	}
	buf.WriteString(`"transactions":`)
	if j.Transactions != nil {
		buf.WriteString(`[`)
		for i, v := range j.Transactions {
			if i != 0 {
				buf.WriteString(`,`)
			}
			/* Struct fall back. type=types.SignedTransaction kind=struct */
			err = buf.Encode(&v)
			if err != nil {
				return err
			}
		}
		buf.WriteString(`]`)
	} else {
		buf.WriteString(`null`)
	}
	buf.WriteString(`,"transaction_ids":`)
	if j.TransactionIDs != nil {
		buf.WriteString(`[`)
		for i, v := range j.TransactionIDs {
			if i != 0 {
				buf.WriteString(`,`)
			}

			{

				obj, err = v.MarshalJSON()
				if err != nil {
					return err
				}
				buf.Write(obj)

			}
		}
		buf.WriteString(`]`)
	} else {
		buf.WriteString(`null`)
	}
	buf.WriteString(`,"extensions":`)

	{

		obj, err = j.Extensions.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte('}')
	return nil
}

const (
	ffjtBlockbase = iota
	ffjtBlocknosuchkey

	ffjtBlockWitness

	ffjtBlockTransactionMerkleRoot

	ffjtBlockWitnessSignature

	ffjtBlockPrevious

	ffjtBlockBlockID

	ffjtBlockTimeStamp

	ffjtBlockSigningKey

	ffjtBlockTransactions

	ffjtBlockTransactionIDs

	ffjtBlockExtensions
)

var ffjKeyBlockWitness = []byte("witness")

var ffjKeyBlockTransactionMerkleRoot = []byte("transaction_merkle_root")

var ffjKeyBlockWitnessSignature = []byte("witness_signature")

var ffjKeyBlockPrevious = []byte("previous")

var ffjKeyBlockBlockID = []byte("block_id")

var ffjKeyBlockTimeStamp = []byte("timestamp")