// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: fullaccount.go

package types

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// Marsha