// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package types

import (
	"fmt"

	"github.com/Assetsadapter/whitecoin-adapter/libs/util"
	"github.com/denkhaus/logging"
	"github.com/juju/errors"
)

type ChainPropertyID struct {
	ObjectID
}

func (p ChainPropertyID) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(p.Instance())); err != nil {
		return errors.Annotate(err, "encode instance")
	}

	return nil
}

func (p *ChainPropertyID) Unmarshal(dec *util.TypeDecoder) error {
	var instance uint64
	if err := dec.DecodeUVarint(&instance); err != nil {
		return errors.Annotate(err, "decode instance")
	}

	p.number = UInt64((uint64(SpaceTypeProtocol) << 56) | (uint64(ObjectTypeChainProperty) << 48) | instance)
	return nil
}

type ChainPropertyIDs []ChainPropertyID

func (p ChainPropertyIDs) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(len(p))); err != nil {
		return errors.Annotate(err, "encode length")
	}

	for _, ex := range p {
		if err := enc.Encode(ex); err != nil {
			return errors.Annotate(err, "encode ChainPropertyID")
		}
	}

	return nil
}

func ChainPropertyIDFromObject(ob GrapheneObject) ChainPropertyID {
	id, ok := ob.(*ChainPropertyID)
	if ok {
		return *id
	}

	p := ChainPropertyID{}
	p.MustFromObject(ob)
	if p.ObjectType() != ObjectTypeChainProperty {
		panic(fmt.Sprintf("inv