// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationTypeTransfer-0]
	_ = x[OperationTypeLimitOrderCreate-1]
	_ = x[OperationTypeLimitOrderCancel-2]
	_ = x[OperationTypeCallOrderUpdate-3]
	_ = x[OperationTypeFillOrder-4]
	_ = x[OperationT