
// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: accountupgradeoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *AccountUpgradeOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *AccountUpgradeOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "account_to_upgrade":`)

	{

		obj, err = j.AccountToUpgrade.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"extensions":`)

	{

		obj, err = j.Extensions.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	if j.UpgradeToLifetimeMember {
		buf.WriteString(`,"upgrade_to_lifetime_member":true`)
	} else {
		buf.WriteString(`,"upgrade_to_lifetime_member":false`)
	}
	buf.WriteByte(',')
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtAccountUpgradeOperationbase = iota
	ffjtAccountUpgradeOperationnosuchkey

	ffjtAccountUpgradeOperationAccountToUpgrade

	ffjtAccountUpgradeOperationExtensions

	ffjtAccountUpgradeOperationUpgradeToLifetimeMember

	ffjtAccountUpgradeOperationFee
)

var ffjKeyAccountUpgradeOperationAccountToUpgrade = []byte("account_to_upgrade")

var ffjKeyAccountUpgradeOperationExtensions = []byte("extensions")

var ffjKeyAccountUpgradeOperationUpgradeToLifetimeMember = []byte("upgrade_to_lifetime_member")

var ffjKeyAccountUpgradeOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - template of ffjson
func (j *AccountUpgradeOperation) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *AccountUpgradeOperation) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtAccountUpgradeOperationbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtAccountUpgradeOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffjKeyAccountUpgradeOperationAccountToUpgrade, kn) {
						currentKey = ffjtAccountUpgradeOperationAccountToUpgrade
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'e':

					if bytes.Equal(ffjKeyAccountUpgradeOperationExtensions, kn) {
						currentKey = ffjtAccountUpgradeOperationExtensions
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffjKeyAccountUpgradeOperationFee, kn) {
						currentKey = ffjtAccountUpgradeOperationFee
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'u':

					if bytes.Equal(ffjKeyAccountUpgradeOperationUpgradeToLifetimeMember, kn) {
						currentKey = ffjtAccountUpgradeOperationUpgradeToLifetimeMember
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyAccountUpgradeOperationFee, kn) {
					currentKey = ffjtAccountUpgradeOperationFee
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffjKeyAccountUpgradeOperationUpgradeToLifetimeMember, kn) {
					currentKey = ffjtAccountUpgradeOperationUpgradeToLifetimeMember
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyAccountUpgradeOperationExtensions, kn) {
					currentKey = ffjtAccountUpgradeOperationExtensions