// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: assetfundfeepooloperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *AssetFundFeePoolOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *AssetFundFeePoolOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "amount":`)
	fflib.FormatBits2(buf, uint64(j.Amount), 10, false)
	buf.WriteString(`,"asset_id":`)

	{

		obj, err = j.AssetID.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"extensions":`)

	{

		obj, err = j.Extensions.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"from_account":`)

	{

		obj, err = j.FromAccount.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtAssetFundFeePoolOperationbase = iota
	ffjtAssetFundFeePoolOperationnosuchkey

	ffjtAssetFundFeePoolOperationAmount

	ffjtAssetFundFeePoolOperationAssetID

	ffjtAssetFundFeePoolOperationExtensions

	ffjtAssetFundFeePoolOperationFromAccount

	ffjtAssetFundFeePoolOperationFee
)

var ffjKeyAssetFundFeePoolOperationAmount = []byte("amount")

var ffjKeyAssetFundFeePoolOperationAssetID = []byte("asset_id")

var ffjKeyAssetFundFeePoolOperationExtensions = []byte("extensions")

var ffjKeyAssetFundFeePoolOperationFromAccount = []byte("from_account")

var ffjKeyAssetFundFeePoolOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - temp