// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: committeememberupdateglobalparametersoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *ChainParameters) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *ChainParameters) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	if j.AllowNonMemberWhitelists {
		buf.WriteString(`{"allow_non_member_whitelists":true`)
	} else {
		buf.WriteString(`{"allow_non_member_whitelists":false`)
	}
	if j.CountNonMemberVotes {
		buf.WriteString(`,"count_non_member_votes":true`)
	} else {
		buf.WriteString(`,"count_non_member_votes":false`)
	}
	buf.WriteString(`,"extensions":`)

	{

		obj,