// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: limitordercreateoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *LimitOrderCreateOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *LimitOrderCreateOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "seller":`)

	{

		obj, err = j.Seller.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	/* Struct fall back. type=types.AssetAmount kind=struct */
	buf.WriteString(`,"amount_to_sell":`)
	err = buf.Encode(&j.AmountToSell)
	if err != nil {
		return err
	}
	/* Struct fall back. type=types.AssetAmount kind=struct */
	buf.WriteString(`,"min_to_receive":`)
	err = buf.Encode(&j.MinToReceive)
	if err != nil {
		return err
	}
	buf.WriteString(`,"expiration":`)

	{

		obj, err = j.Expiration.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	if j.FillOrKill {
		buf.WriteString(`,"fill_or_kill":true`)
	} else {
		buf.WriteString(`,"fill_or_kill":false`)
	}
	buf.WriteString(`,"extensions":`)

	{

		obj, err = j.Extensions.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtLimitOrderCreateOperationbase = iota
	ffjtLimitOrderCreateOperationnosuchkey

	ffjtLimitOrderCreateOperationSeller

	ffjtLimitOrderCreateOperationAmountToSell

	ffjtLimitOrderCreateOperationMinToReceive

	ffjtLimitOrderCreateOperationExpiration

	ffjtLimitOrderCreateOperationFillOrKill

	ffjtLimitOrderCreateOperationExtensions

	ffjtLimitOrderCreateOperationFee
)

var ffjKeyLimitOrderCreateOperationSeller = []byte("seller")

var ffjKeyLimitOrderCreateOperationAmountToSell = []byte("amount_to_sell")

var ffjKeyLimitOrderCreateOperationMinToReceive = []byte("min_to_receive")

var ffjKeyLimitOrderCreateOperationExpiration = []byte("expiration")

var ffjKeyLimitOrderCreateOperationFillOrKill = []byte("fill_or_kill")

var ffjKeyLimitOrderCreateOperationExtensions = []byte("extensions")

var ffjKeyLimitOrderCreateOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - template of ffjson
func (j *LimitOrderCreateOperation) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *LimitOrderCreateOperation) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtLimitOrderCreateOperationbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtLimitOrderCreateOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffjKeyLimitOrderCreateOperationAmountToSell, kn) {
						currentKey = ffjtLimitOrderCreateOperationAmountToSell
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'e':

					if bytes.Equal(ffjKeyLimitOrderCreateOperationExpiration, kn) {
						currentKey = ffjtLimitOrderCreateOperationExpiration
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyLimitOrderCreateOperationExtensions, kn) {
						currentKey = ffjtLimitOrderCreateOperationExtensions
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffjKeyLimitOrderCreateOperationFillOrKill, kn) {
						currentKey = ffjtLimitOrderCreateOperationFillOrKill
						state = ffl