
// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: withdrawpermissionclaimoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *WithdrawPermissionClaimOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *WithdrawPermissionClaimOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "withdraw_permission":`)

	{

		obj, err = j.WithdrawPermission.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"withdraw_from_account":`)

	{

		obj, err = j.WithdrawFromAccount.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"withdraw_to_account":`)

	{

		obj, err = j.WithdrawToAccount.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	/* Struct fall back. type=types.AssetAmount kind=struct */
	buf.WriteString(`,"amount_to_withdraw":`)
	err = buf.Encode(&j.AmountToWithdraw)
	if err != nil {
		return err
	}
	buf.WriteByte(',')
	if j.Memo != nil {
		if true {
			/* Struct fall back. type=types.Memo kind=struct */
			buf.WriteString(`"memo":`)
			err = buf.Encode(j.Memo)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtWithdrawPermissionClaimOperationbase = iota
	ffjtWithdrawPermissionClaimOperationnosuchkey

	ffjtWithdrawPermissionClaimOperationWithdrawPermission

	ffjtWithdrawPermissionClaimOperationWithdrawFromAccount

	ffjtWithdrawPermissionClaimOperationWithdrawToAccount

	ffjtWithdrawPermissionClaimOperationAmountToWithdraw

	ffjtWithdrawPermissionClaimOperationMemo

	ffjtWithdrawPermissionClaimOperationFee
)

var ffjKeyWithdrawPermissionClaimOperationWithdrawPermission = []byte("withdraw_permission")

var ffjKeyWithdrawPermissionClaimOperationWithdrawFromAccount = []byte("withdraw_from_account")

var ffjKeyWithdrawPermissionClaimOperationWithdrawToAccount = []byte("withdraw_to_account")

var ffjKeyWithdrawPermissionClaimOperationAmountToWithdraw = []byte("amount_to_withdraw")

var ffjKeyWithdrawPermissionClaimOperationMemo = []byte("memo")

var ffjKeyWithdrawPermissionClaimOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - template of ffjson
func (j *WithdrawPermissionClaimOperation) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *WithdrawPermissionClaimOperation) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtWithdrawPermissionClaimOperationbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtWithdrawPermissionClaimOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationAmountToWithdraw, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationAmountToWithdraw
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationFee, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationFee
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'm':

					if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationMemo, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationMemo
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'w':

					if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationWithdrawPermission, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationWithdrawPermission
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationWithdrawFromAccount, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationWithdrawFromAccount
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyWithdrawPermissionClaimOperationWithdrawToAccount, kn) {
						currentKey = ffjtWithdrawPermissionClaimOperationWithdrawToAccount
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyWithdrawPermissionClaimOperationFee, kn) {
					currentKey = ffjtWithdrawPermissionClaimOperationFee
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyWithdrawPermissionClaimOperationMemo, kn) {
					currentKey = ffjtWithdrawPermissionClaimOperationMemo
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffjKeyWithdrawPermissionClaimOperationAmountToWithdraw, kn) {
					currentKey = ffjtWithdrawPermissionClaimOperationAmountToWithdraw
					state = fflib.FFParse_want_colon
					goto mainparse
				}
