// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: workercreateoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *WorkerCreateOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *WorkerCreateOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "daily_pay":`)
	fflib.FormatBits2(buf, uint64(j.DailyPay), 10, false)
	buf.WriteString(`,"initializer":`)

	{

		obj, err = j.Initializer.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"name":`)
	fflib.WriteJsonString(buf, string(j.Name))
	buf.WriteString(`,"owner":`)

	{

		obj, err = j.Owner.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"url":`)
	fflib.WriteJsonString(buf, string(j.URL))
	buf.WriteString(`,"work_begin_date":`)

	{

		obj, err = j.WorkBeginDate.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"work_end_date":`)

	{

		obj, err = j.WorkEndDate.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtWorkerCreateOperationbase = iota
	ffjtWorkerCreateOperationnosuchkey

	ffjtWorkerCreateOperationDailyPay

	ffjtWorkerCreateOperationInitializer

	ffjtWorkerCreateOperationName

	ffjtWorkerCreateOperationOwner

	ffjtWorkerCreateOperationURL

	ffjtWorkerCreateOperationWorkBeginDate

	ffjtWorkerCreateOperationWorkEndDate

	ffjtWorkerCreateOperationFee
)

var ffjKeyWorkerCreateOperationDailyPay = []byte("daily_pay")

var ffjKeyWorkerCreateOperationInitializer = []byte("initializer")

var ffjKeyWorkerCreateOperationName = []byte("name")

var ffjKeyWorkerCreateOperationOwner = []byte("owner")

var ffjKeyWorkerCreateOperationURL = []byte("url")

var ffjKeyWorkerCreateOperationWorkBeginDate = []byte("work_begin_date")

var ffjKeyWorkerCreateOperationWorkEndDate = []byte("work_end_date")

var ffjKeyWorkerCreateOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - template of ffjson
func (j *WorkerCreateOperation) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *WorkerCreateOperation) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtWorkerCreateOperationbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtWorkerCreateOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'd':

					if bytes.Equal(ffjKeyWorkerCreateOperationDailyPay, kn) {
						currentKey = ffjtWorkerCreateOperationDailyPay
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffjKeyWorkerCreateOperationFee, kn) {
						currentKey = ffjtWorkerCreateOperationFee
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'i':

					if bytes.Equal(ffjKeyWorkerCreateOperationInitializer, kn) {
						currentKey = ffjtWorkerCreateOperationInitializer
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'n':

					if bytes.Equal(ffjKeyWorkerCreateOperationName, kn) {
						currentKey = ffjtWorkerCreateOperationName
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'o':

					if bytes.Equal(ffjKeyWorkerCreateOperationOwner, kn) {
						currentKey = ffjtWorkerCreateOperationOwner
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'u':

					if bytes.Equal(ffjKeyWorkerCreateOperationURL, kn) {
						currentKey = ffjtWorkerCreateOperationURL
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'w':

					if bytes.Equal(ffjKeyWorkerCreateOperationWorkBeginDate, kn) {
						currentKey = ffjtWorkerCreateOperationWorkBeginDate
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyWorkerCreateOperationWorkEndDate, kn) {
						currentKey = ffjtWorkerCreateOperationWorkEndDate
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyWorkerCreateOperationFee, kn) {
					currentKey = ffjtWorkerCreateOperationFee
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyWorkerCreateOperationWorkEndDate, kn) {
					currentKey = ffjtWorkerCreateOperationWorkEndDate
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyWorkerCreateOperationWorkBeginDate, kn) {
					currentKey = ffjtWorkerCreateOperationWorkBeginDate
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyWorkerCreateOperationURL, kn) {
					currentKey = ffjtWorkerCreateOperationURL
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyWorkerCreateOperationOwner, kn) {
					currentKey = ffjtWorkerCreateOperationOwner
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyWorkerCreateOperationName, kn) {
					currentKey = ffjtWorkerCreateOperationName
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyWorkerCreateOperationInitializer, kn) {
					currentKey = ffjtWorkerCreateOperationInitializer
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffjKeyWorkerCreateOperationDailyPay, kn) {
					currentKey = ffjtWorkerCreateOperationDailyPay
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtWorkerCreateOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTo